/// <reference types="node" />
import {beforeAll,afterAll,it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
let db:PGlite;
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;
create function is_actief() returns boolean language sql as $$select current_setting('test.active',true)='yes'$$;
create function is_supporter_account() returns boolean language sql as $$select current_setting('test.supporter',true)='yes'$$;
create table supporter_profiles(user_id uuid,naam text,actief boolean);
create table supporter_attendance(user_id uuid,match_key text,status text);
create table matches(match_key text,seizoen text,datum date,uur text,thuis_id int,uit_id int,status text,thuis text,uit text,bron text);
create function match_aftrap(date,text) returns timestamptz language sql as $$select $1::timestamptz$$;
insert into supporter_profiles values('00000000-0000-0000-0000-000000000001','Fan',true);
insert into matches values('echt','2020-2021','2020-09-01','15:00',152,1,'gespeeld','Steca','Ploeg','scrape'),('proef','2020-2021','2020-09-01','15:00',152,1,'gespeeld','Steca','Proef','push-test');
insert into supporter_attendance values('00000000-0000-0000-0000-000000000001','echt','aanwezig');`);
const s=readFileSync(new URL('../../../supabase/app_schema.sql',import.meta.url),'utf8');await db.exec(s.slice(s.indexOf('-- Supportersklassement: uitsluitend echte')).split('-- Supporteraccount beheren,')[0]);},30000);
afterAll(async()=>{await db?.close();});
it('weigert ongeauthenticeerde toegang en anonieme RPC-rechten',async()=>{await expect(db.query('select supporter_klassement_data()')).rejects.toThrow('Log in');expect((await db.query<{ok:boolean}>("select has_function_privilege('anon','supporter_klassement_data()','EXECUTE') ok")).rows[0].ok).toBe(false);});
it('geeft echte data aan supporters zonder testbadges of testmatches',async()=>{await db.exec("select set_config('test.supporter','yes',false)");const r=await db.query<{d:{personen:unknown[],matches:{id:string}[],afgerond:string[],bezoeken:unknown[],testbadges:unknown[]}}>('select supporter_klassement_data() d');expect(r.rows[0].d).toMatchObject({matches:[{id:'echt'}],afgerond:['2020-2021'],testbadges:[]});expect(r.rows[0].d.personen).toHaveLength(1);expect(r.rows[0].d.bezoeken).toHaveLength(1);});
it('neemt een nieuw account meteen op met nul bezoeken',async()=>{await db.exec("insert into supporter_profiles values('00000000-0000-0000-0000-000000000002','Nieuwe fan',true)");const r=await db.query<{d:{personen:unknown[],bezoeken:unknown[]}}>('select supporter_klassement_data() d');expect(r.rows[0].d.personen).toHaveLength(2);expect(r.rows[0].d.bezoeken).toHaveLength(1);});
